//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Tool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_ToolTYPE                    130
#define IDD_MYFORMVIEW                  310
#define IDD_TERRAIN_DLG                 312
#define IDD_MESH_DLG                    314
#define IDD_DATA_TAB                    316
#define IDD_EFFECT_DLG                  319
#define IDD_CAM_DLG                     320
#define IDD_EVENT_DLG                   321
#define IDD_DYNAMIC_MONSTER             321
#define IDD_TERRAIN_TOOL                325
#define IDD_STATIC_MESH_DLG             327
#define IDD_DYNAMIC_MESH_DLG            333
#define IDD_PREFAB_DLG                  335
#define IDD_TERRAIN_MESH_DLG            337
#define IDD_PATH_DLG                    339
#define IDD_DYNAMIC_CONTROLLER_DIALOG   341
#define IDC_TAB1                        1000
#define ID_TERRAIN_SAVE                 1001
#define ID_TERRAIN__LOAD                1002
#define ID_MESH_SAVE                    1003
#define ID_MESH_LOAD                    1004
#define ID_DATA_LOAD                    1005
#define IDC_LIST1                       1008
#define IDC_DELETE_NAVI_MESH            1009
#define IDC_MODIFY_NAVI_MESH            1010
#define IDC_WIREFRAME                   1012
#define IDC_SOLID                       1013
#define IDC_TERRAIN_TEX_APPLY           1013
#define IDC_TERRAINTEX_X_INPUT          1014
#define IDC_TERRAINTEX_X_INPUT2         1015
#define IDC_VTX_ITV_INPUT               1016
#define IDC_MAP_DETAIL                  1017
#define IDC_TERRAIN_CONTROL             1020
#define IDC_NAVI_CONTROL                1021
#define IDC_CELL_DELETE                 1028
#define IDC_NAVI_X_POS                  1030
#define IDC_NAVI_X_SPIN                 1031
#define IDC_NAVI_Y_POS                  1032
#define IDC_NAVI_Y_SPIN                 1034
#define IDC_NAVI_Z_POS                  1035
#define IDC_NAVI_Z_SPIN                 1036
#define IDC_TERRAIN_SAVE                1037
#define IDC_TERRAIN_LOAD                1038
#define IDC_STATIC_MESH_SAVE            1039
#define IDC_STATIC_MESH_LOAD            1040
#define IDC_TREE_STATIC_OBJ             1042
#define IDC_STATIC_MESH_DELETE          1044
#define IDC_STATIC_MESH_POS_X           1045
#define IDC_STATIC_MESH_POS_X_SPIN      1046
#define IDC_STATIC_MESH_POS_Y_EDIT      1047
#define IDC_STATIC_MESH_Y_POS_SPIN      1048
#define IDC_STATIC_MESH_POS_Z_EDIT      1049
#define IDC_STATIC_MESH_Z_POS_SPIN      1050
#define IDC_STATIC_MESH_SCALE_POS_X     1051
#define IDC_STATIC_MESH_SCALE_X_SPIN    1052
#define IDC_STATIC_MESH_POS_Y_SCALE     1053
#define IDC_STATIC_MESH_SCALE_Y_SPIN    1054
#define IDC_STATIC_MESH_SCALE_Z         1055
#define IDC_STATIC_MESH_SPIN_Z          1056
#define IDC_STATIC_MESH_LOOK_X          1057
#define IDC_STATIC_MESH_SPIN_X          1058
#define IDC_STATIC_MESH_LOOK_Y          1059
#define IDC_STATIC_MESH_SPIN_Y          1060
#define IDC_STATIC_MESH_LOOK_Z          1061
#define IDC_STATIC_MESH_LOOK_Z_SPIN     1062
#define IDC_BUTTON_STATIC_MESH_CLONE    1064
#define IDC_DYNAMIC_POS_X_EDIT          1070
#define IDC_DYNAMIC_POS_X_SPIN          1071
#define IDC_DYNAMIC_POS_Y_EDIT          1072
#define IDC_DYNAMIC_POS_Y_SPIN          1073
#define IDC_DYNAMIC_POS_Z_EDIT          1074
#define IDC_DYNAMIC_POS_Z_SPIN          1075
#define IDC_DYNAMIC_SCALE_EDIT          1076
#define IDC_DYNAMIC_SCALE_X_SPIN        1077
#define IDC_DYNAMIC_SCALE_Y_EDIT        1078
#define IDC_DYNAMIC_SCALE_Y_SPIN        1079
#define IDC_DYNAMIC_SCALE_Z_EDIT        1080
#define IDC_DYNAMIC_SCALE_Z_SPIN        1081
#define IDC_DYNAMIC_ROT_X_EDIT          1082
#define IDC_DYNAMIC_ROT_X_SPIN          1083
#define IDC_DYNAMIC_ROT_Y_EDIT          1084
#define IDC_DYNAMIC_ROT_Y_SPIN          1085
#define IDC_DYNAMIC_ROT_Z_EDIT          1086
#define IDC_DYNAMIC_ROT_Z_SPIN          1087
#define IDC_DYNAMIC_MESH_SAVE           1088
#define IDC_DYNAMIC_MESH_LOAD           1089
#define IDC_TERRAIN_MESH_NAME           1090
#define IDC_TERRAIN_MESH_CLONE          1091
#define IDC_TERRAIN_POS_X               1092
#define IDC_TERRAIN_POS_X_SPIN          1093
#define IDC_TERRAIN_POS_Y               1094
#define IDC_TERRAIN_POS_Y_SPIN          1095
#define IDC_TERRAIN_POS_Z               1096
#define IDC_TERRAIN_POS_Z_SPIN          1097
#define IDC_TERRAIN_SCALE_X             1098
#define IDC_TERRAIN_SCALE_X_SPIN        1099
#define IDC_TERRAIN_SCALE_Y             1100
#define IDC_TERRAIN_SCALE_Y_SPIN        1101
#define IDC_TERRAIN_SCALE_Z             1102
#define IDC_TERRAIN_SCALE_Z_SPIN        1103
#define IDC_TERRAIN_ANGLE_X             1104
#define IDC_TERRAIN_ANGLE_X_SPIN7       1105
#define IDC_TERRAIN_ANGLE_Y             1106
#define IDC_TERRAIN_ANGLE_Y_SPIN8       1107
#define IDC_TERRAIN_ANGLE_Z             1108
#define IDC_TERRAIN_ANGLE_Z_SPIN        1109
#define IDC_ANIMATE_BUTTON              1113
#define IDC_PREFAB_LIST                 1117
#define IDC_PREFAB_CHANGE_APPLY_BUTTON  1119
#define IDC_BONE_COLLIDER_APPLY_BUTTON  1122
#define IDC_BONE_COLLIDER_DELETE_BUTTON 1123
#define IDC_PREFAB_SAVE_BUTTON          1124
#define IDC_PREFAB_LOAD_BUTTON          1125
#define IDC_COLLIDER_RADIUS_EDIT        1129
#define IDC_TERRAIN_SAVE_BUTTON         1132
#define IDC_TERRAIN_LOAD_BUTTON         1133
#define IDC_STATIC_SPHERE_RADIUS_EDIT   1134
#define IDC_STATIC_SPHERE_RADIUS_SPIN   1135
#define IDC_STATIC_MESH_SPHERE_CREATE_BUTTON 1136
#define IDC_DATA_TAB                    1137
#define IDC_STATIC_MESH_COUNT_EDIT      1138
#define IDC_DYNAMIC_MESH_COUNT_EDIT     1139
#define IDC_TEXTURE_COUNT_EDIT          1140
#define IDC_PATH_SAVE_BUTTON            1141
#define IDC_COUNT_SAVE_BUTTON           1143
#define IDC_PREFAB_SCALE_X_EDIT         1146
#define IDC_PREFAB_SCALE_X_SPIN         1147
#define IDC_PREFAB_SCALE_Y_EDIT         1148
#define IDC_PREFAB_SCALE_Y_SPIN         1149
#define IDC_PREFAB_SCLAE_Z_EDIT         1150
#define IDC_PREFAB_SCALE_Z_SPIN         1151
#define IDC_FREFAB_CLONE_BUTTON         1152
#define IDC_NAVI_DEFAULT_Y_BUTTON       1154
#define IDC_COL_RENDER_CHECK            1155
#define IDC_GROUP_PLAYER_RADIO          1156
#define IDC_GROUP_NPC_RADIO             1157
#define IDC_GROUP_MONSTER_RADIO         1158
#define IDC_DELETE_BUTTON               1160
#define IDC_Z_MOVE_0_0_1_RADIO          1161
#define IDC_Z_MOVE_0_1_RADIO            1162
#define IDC_Z_MOVE_1_0_RADIO            1163
#define IDC_COMBO1                      1165
#define IDC_PREFAB_ACTION_COMBO         1166
#define IDC_COMBO2                      1167
#define IDC_COMBO3                      1168
#define IDC_ACTION_COL_COMBO            1172
#define IDC_ACTION_NAME_EDIT            1173
#define IDC_COOL_TIME_EDIT              1174
#define IDC_BUTTON1                     1175
#define IDC_EDIT3                       1176

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        343
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1177
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
