#ifndef Enum_h__
#define Enum_h__

enum RESOURCEID { RESOURCE_STATIC, RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_END };
enum LOADINGID { LOADING_STAGE, LOADING_BOSS, LOADING_END };

enum FRAME_ENUM { FRAME_60, FPS_END };
enum TIMER_ENUM { TIMER_60FPS, TIMER_IMMEDIATE, TIMER_END };

// 씬 체인지용
enum SCENE_TYPE { SCENE_LOGO, SCENE_STAGE, SCENE_END };

// 각 씬에 필요한 레이어 계층
enum LOGO_MAP { LOGO_DEFAULT, LOGO_END };
enum STAGE_MAP { STAGE_DEFAULT, STAGE_END };

enum LOGO_OBJ { LOGO_UI, LOGO_OBJECT, LOGO_OBJ_END };
enum STAGE_OBJ { STAGE_PARTICLE, STAGE_PLAYER, STAGE_MONSTER, STAGE_TERRAIN, STAGE_BULLET, STAGE_OBJECTS, STAGE_UI, STAGE_OBJ_END };

enum CAMERA_ENUM { STATIC_CAMERA, DYNAMIC_CAMERA, FIRST_PERSON_VIEW, CAMERA_END };

enum MOUSE_ENUM { FIELD_MOUSE, INVENTORY_MOUSE, MOUSE_END };

enum POOL_ENUM { POOL_BULLET, POOL_PARTICLE, POOL_GUNFIRE, POOL_FRAGMENT, POOL_VOMIT, POOL_FIREWORK, POOL_END };

enum ITEM_TYPE { ITEM_WEAPON, ITEM_ARMOR, ITEM_USABLE, ITEM_INSTALL, ITEM_END };

enum WEAPON		{ RIFLE, SHOT_GUN, CHAIN_SAW, WEAPON_END };

enum MATERIAL_TYPE	{ MATERIAL_WOOD, MATERIAL_STONE, MATERIAL_END };

enum INSTALL_TYPE	{ INSTALL_WALL, INSTALL_MACHINE_GUN, INSTALL_END };

enum OBJECT_STATUS	{ ATTACK, IDLE, DIE, MOVE, STATUS_END};

#endif // Enum_h__