#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum COMPONENTID	{ ID_DYNAMIC, ID_STATIC, ID_END };

	enum WINMODE		{ MODE_FULL, MODE_WIN };

	enum INFO			{ INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION		{ ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum BUFFERID		{ BUFFER_TRICOL, BUFFER_RCCOL, BUFFER_RCTEX, BUFFER_TERRAINTEX, BUFFER_CUBETEX };
	enum TEXTURETYPE	{ TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID		{ RENDER_PRIORITY, RENDER_PREUI, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_END };

	enum COLLTYPE		{ COL_FALSE, COL_ATTACK_START, COL_DURING_ATTACK, COL_TRUE, COL_END };

	enum MESHTYPE		{ TYPE_STATIC, TYPE_DYNAMIC, TYPE_NAVI };

	enum MOUSEKEYSTATE	{ DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };
}

#endif // Engine_Enum_h__
